### ISSUE TITLE
[BUG] Rotation doesn't work as expected

### ISSUE THREAD

**Issue by findmyway** [Wikunia/Javis.jl#220] opened 2020-10-04 07:15 UTC
**Before Filing a Report**

- [x] Did I read the Documentation and/or docstrings?
- [x] Did I search the Javis GitHub to see if this bug has already been reported?
- [x] Am I familiar with the Javis philosophy?

**Describe the bug**

When applying a `Rotation` to an object to rotate it around a center, the object seems to be simply shifted first and then rotate. While I expect the object to rotate around the **center** I specified.

**To Reproduce**

1. Julia Version (i.e. output of `julia -v`):

```julia
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-1630 v3 @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
```

2. Operating system (Mac, Linux, Windows): Windows

3. Minimum working code example that led to bug:
```julia
using Javis
video = Video(600, 400)
function ground(args...)
    background("black")
    sethue("white")
end
javis(video, [
           BackgroundAction(1:100, ground),
           Action(1:100, (args...)->poly((sethue("red");[Point(50, 0), Point(100,0), Point(50, -50)]), :fill, close=true); subactions=[
               SubAction(25:50, Rotation(0., -π/2, Point(50, 0))),
           ]),
       ]; pathname="test.gif")
```

**Screenshots**
If applicable, add your gif or drawing to help explain your problem.

![test](https://user-images.githubusercontent.com/5612003/95009377-35872180-0654-11eb-84f5-b27d9c1b9879.gif)

As you can see, after step 25, the triangle jumps to `Point(100, 0)` and then rotate around `Point(50,0)`.

**Comment by Wikunia** [comment] 2020-10-04 07:24
Thanks for opening the issue. I'm currently not able to test my theory but I am quite sure that the problem is the following:
`Rotation` rotates the canvas and not the object. The reason is that Javis doesn't really know what it is drawing before it draws it. 
The standard fix for this is:
- Have the polygon start at the origin (more precisely the corner you would like to rotate around)
- Use `SubAction(1:1, Translation (Point (x,y)))` to translate it without any animation to the point it should be
- then use rotation

Hope this works and sorry for the inconveniences. We should document this better. Unfortunately I can't think of a different way to make the intuitive code that you wrote work in a general case.

**Comment by findmyway** [comment] 2020-10-04 07:30
Thanks for your quick response.

That's an interesting fix😂 But it just works!

Hope it can be addressed in the future.

**Comment by Wikunia** [comment] 2020-10-04 07:32
In general it is best to always have the drawing in the center and then shift it over as the first SubAction.

**Comment by findmyway** [comment] 2020-10-04 10:21
Thanks for your trick. I just made my first animation using Javis.jl (The logo for the project [ReinforcementLearningZoo.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl)) 🎉 

![](https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/raw/master/docs/logo/logo.gif)

**Comment by Wikunia** [comment] 2020-10-04 10:24
Great! Looks awesome

**Comment by TheCedarPrince** [comment] 2020-10-26 19:30
Linked #232 to discuss how to work around/with this behavior in v0.3

**Comment by Wikunia** [comment] 2020-11-09 22:15
I think we have better way to deal with rotations now using `anim_rotate` and `anim_rotate_around` and have the tutorial changed in a way that we define things at the origin and translate them later which makes this easier.

**Comment by TheCedarPrince** [comment] 2020-11-09 22:36
I agree @Wikunia - feel free to close this when desired.

**Closed** 2020-11-09 23:18 UTC
Labels: bug
