### ISSUE TITLE
[BUG] mp4 Very Choppy

### ISSUE THREAD

**Issue by markhalonen** [Wikunia/Javis.jl#329] opened 2021-04-14 14:09 UTC
When I create an mp4, the frames seem out of order for an animation. If I step frame by frame, the animation goes forward and backward in a very choppy fashion.

**To Reproduce**

1. Julia Version (i.e. output of `julia -v`): __1.6__

2. Operating system (Mac, Linux, Windows): __Mac__

3. Javis version (i.e output of `] status Javis` in the REPL): __v0.5.0__

4. Minimum working code example that led to bug: I just took [Tutorial 1](https://wikunia.github.io/Javis.jl/stable/tutorials/tutorial_1/) and changed `gif` to `mp4`:

```julia
using Javis

function ground(args...)
    background("white") # canvas background
    sethue("black") # pen color
end

function object(p=O, color="black")
    sethue(color)
    circle(p, 25, :fill)
    return p
end

function path!(points, pos, color)
    sethue(color)
    push!(points, pos) # add pos to points
    circle.(points, 2, :fill) # draws a circle for each point using broadcasting
end

function connector(p1, p2, color)
    sethue(color)
    line(p1,p2, :stroke)
end

myvideo = Video(500, 500)

path_of_red = Point[]
path_of_blue = Point[]

Background(1:70, ground)
red_ball = Object(1:70, (args...)->object(O, "red"), Point(100,0))
act!(red_ball, Action(anim_rotate_around(2π, O)))
blue_ball = Object(1:70, (args...)->object(O, "blue"), Point(200,80))
act!(blue_ball, Action(anim_rotate_around(2π, 0.0, red_ball)))
Object(1:70, (args...)->connector(pos(red_ball), pos(blue_ball), "black"))
Object(1:70, (args...)->path!(path_of_red, pos(red_ball), "red"))
Object(1:70, (args...)->path!(path_of_blue, pos(blue_ball), "blue"))

render(myvideo; pathname="tutorial_1.mp4")
```

**Expected Behavior and Actual Behavior**
I expected an mp4 with the frames in order. I got an mp4 with frames out of order and very choppy. 

**Screenshots**
If applicable, add your gif or drawing to help explain your problem.

https://user-images.githubusercontent.com/7853605/114724284-61711700-9d09-11eb-813d-9e031bed84b2.mp4

**Comment by Wikunia** [comment] 2021-04-14 14:17
Thanks for posting the issue. Can you confirm that everything works fine with `.gif`?

**Comment by markhalonen** [comment] 2021-04-14 14:19
Yes, gif looks good:

![tutorial_1](https://user-images.githubusercontent.com/7853605/114725893-e6106500-9d0a-11eb-92d8-22e7282c737a.gif)


I used the `tempdirectory` and inspected the images, they are all in order...

**Comment by Wikunia** [comment] 2021-04-14 14:26
Hmm okay good to know. I can't reproduce this behavior on my machine. 
Generating mp4 is a bit more complex than the gif but normally doesn't break like this. 
What is the result of 
```
] status VideoIO
```

**Comment by markhalonen** [comment] 2021-04-14 14:28
```
(Steelhead) pkg> status VideoIO
     Project Steelhead v0.1.0
  No Matches in `~/Freelance/LauriumLabs/st/Steelhead.jl/Project.toml`

(Steelhead) pkg>
```

**Comment by Wikunia** [comment] 2021-04-14 14:30
okay you might need to add it first to see which version is used for Javis :smile: I forgot how this works...
Do you mind running:
```
] add VideoIO
] status VideoIO
] rm VideoIO
```

**Comment by markhalonen** [comment] 2021-04-14 14:34
```
(Steelhead) pkg> add VideoIO

(Steelhead) pkg> status VideoIO
     Project Steelhead v0.1.0
      Status `~/Freelance/LauriumLabs/st/Steelhead.jl/Project.toml`
  [d6d074c3] VideoIO v0.8.4

(Steelhead) pkg> rm VideoIO
    Updating `~/Freelance/LauriumLabs/st/Steelhead.jl/Project.toml`
  [d6d074c3] - VideoIO v0.8.4
  No Changes to `~/Freelance/LauriumLabs/st/Steelhead.jl/Manifest.toml`

(Steelhead) pkg>
```

**Comment by Wikunia** [comment] 2021-04-14 14:37
Thanks okay that's the same version I have installed. One thing I can't test is running it on Mac and I think @TheCedarPrince also doesn't have one available. Maybe he has an idea why this is failing. 
One thing we can do is running it in non silent mode to maybe catch what's going wrong. In the mean time generating an mp4 from the single frames should work with a simple ffmpeg command before we are able to checkout what's happening in this case.

**Comment by TheCedarPrince** [comment] 2021-04-14 15:09
Hey @markhalonen and @Wikunia - I do have a Mac we could try reproducing this on. I will circle back to this a bit later tonight to see if I can get it all working. FWIW, I have never seen that error before which leads me to think there is some rendering issue happening that doesn't directly involve just Javis.

**Comment by codejaeger** [comment] 2021-04-14 15:17
I am on a Mac and I tried this out. Although I don't have an idea as to why this is happening, an interesting observation is that it seems this issue is also specific to the video player used for rendering. On Mac's Quicktime player, this can be reproduced. However it does not appear on VLC media player. I think @TheCedarPrince is right, this issue might not be related only to Javis.

**Comment by markhalonen** [comment] 2021-04-14 16:51
- I generated on Linux and still is choppy on Mac QuickTime.
- I uploaded to Vimeo and it is smooth.
- Playing on VLC on Mac is smooth

So it seems QuickTime and the GitHub player both have issues with this mp4 but not other players, interesting!

**Comment by TheCedarPrince** [comment] 2021-04-14 22:15
@markhalonen - as this is not really related to Javis, I am going to close this issue. However, if you continue to have more issues, I would suggest you open an issue with [ffmpeg](https://github.com/FFmpeg/FFmpeg). Please let us know if you have any more issues. Otherwise, thank you for using Javis and have a wonderful day!

Thanks @codejaeger to testing this out for us. Many thanks!

**Closed by TheCedarPrince** 2021-04-14 22:15 UTC
Labels: bug
